spring:
  datasource:
    url: jdbc:h2:mem:test
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#  sql:
#    init:
#      data-locations: classpath*:db/h2/data.sql
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GOOGLE_ID}
    password: ${GOOGLE_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable:
              true
            required:
              true
          auth:
            true

jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420